{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "ray-plugin",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ray-plugin-1.3.0.jar",
          "url": "ray-plugin-1.3.0.jar",
          "size": 12533,
          "sha512": "52cb82c82d4a445e0ffb30831639a189e9167fefb22189f17701067e57bffdb816dd39b29f6b34ee790e729f537b1904587b5b4050ed88f39d524ff7659cae53",
          "sha256": "f9f5608450b2c1f704e68f6a6364efebaeb88d4c117ecb426c6d97f19e6ef735",
          "sha1": "db6ec503f35f8d4ba03d1668f28894d98ceeb416",
          "md5": "11c2b27f2865380f06ff8c8724e196f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ray-plugin-1.3.0.jar",
          "url": "ray-plugin-1.3.0.jar",
          "size": 12533,
          "sha512": "52cb82c82d4a445e0ffb30831639a189e9167fefb22189f17701067e57bffdb816dd39b29f6b34ee790e729f537b1904587b5b4050ed88f39d524ff7659cae53",
          "sha256": "f9f5608450b2c1f704e68f6a6364efebaeb88d4c117ecb426c6d97f19e6ef735",
          "sha1": "db6ec503f35f8d4ba03d1668f28894d98ceeb416",
          "md5": "11c2b27f2865380f06ff8c8724e196f4"
        }
      ]
    }
  ]
}
