{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "ray-plugin",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ray-plugin-1.3.0.jar",
          "url": "ray-plugin-1.3.0.jar",
          "size": 12642,
          "sha512": "8d4c4dd2219c94354873128f144b8a2753dc37ac60995fa948de3f5c8459d023c2434371a23652acb53d0c11d36c27e92681927a03083ba0a0d6dbce614a10d6",
          "sha256": "a1fd0c681c9759c5b85d49be8aa46cd7d55a7d9ae2779c20c3a136cd1a839ee7",
          "sha1": "7450cf5924ecd78feab60f03ceef87aeed2e9fe9",
          "md5": "c130004f14681b0a6dbf7d2fd9e28d3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ray-plugin-1.3.0.jar",
          "url": "ray-plugin-1.3.0.jar",
          "size": 12642,
          "sha512": "8d4c4dd2219c94354873128f144b8a2753dc37ac60995fa948de3f5c8459d023c2434371a23652acb53d0c11d36c27e92681927a03083ba0a0d6dbce614a10d6",
          "sha256": "a1fd0c681c9759c5b85d49be8aa46cd7d55a7d9ae2779c20c3a136cd1a839ee7",
          "sha1": "7450cf5924ecd78feab60f03ceef87aeed2e9fe9",
          "md5": "c130004f14681b0a6dbf7d2fd9e28d3d"
        }
      ]
    }
  ]
}
