{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "ray-plugin",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ray-plugin-1.3.0.jar",
          "url": "ray-plugin-1.3.0.jar",
          "size": 12590,
          "sha512": "5765be0814c8757da4be826ca9a84c3618f78629ab83e85aafade30d6cefe7324ed16878ed15c2fc5ecf1764ef137ebafb511b4aac6c1366fbec9f97221e5b49",
          "sha256": "72b4c926440b6138242c06c90e42c310d619572601a0691d5e64ffa8c3b7d0e1",
          "sha1": "314e456b2e11dcf3a0f238b62e52efaddc947837",
          "md5": "630d3ab56d06a31dc3e1b21b939057d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ray-plugin-1.3.0.jar",
          "url": "ray-plugin-1.3.0.jar",
          "size": 12590,
          "sha512": "5765be0814c8757da4be826ca9a84c3618f78629ab83e85aafade30d6cefe7324ed16878ed15c2fc5ecf1764ef137ebafb511b4aac6c1366fbec9f97221e5b49",
          "sha256": "72b4c926440b6138242c06c90e42c310d619572601a0691d5e64ffa8c3b7d0e1",
          "sha1": "314e456b2e11dcf3a0f238b62e52efaddc947837",
          "md5": "630d3ab56d06a31dc3e1b21b939057d8"
        }
      ]
    }
  ]
}
