{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.4.5.jar",
          "url": "common-1.4.5.jar",
          "size": 16518,
          "sha512": "93bb053538adc7202394f78487965fbc47ff03402932d8dba88c8ea6f0c571e5a31a57d3c65e2ae238d7b11ba86b2f46aea29c8b16df3c8fd3db61658deedaa6",
          "sha256": "fab4d2241a16a0ffeff129b4125851f105fa4d80882cc0d2101c25b7b1fb29c6",
          "sha1": "06d4784649bb7cd6e35323c30cc66a6d36236e1a",
          "md5": "c62121c77b8c4943356269f96ba7a905"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "tools",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "7.0.0.202409031743-r"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.4.5.jar",
          "url": "common-1.4.5.jar",
          "size": 16518,
          "sha512": "93bb053538adc7202394f78487965fbc47ff03402932d8dba88c8ea6f0c571e5a31a57d3c65e2ae238d7b11ba86b2f46aea29c8b16df3c8fd3db61658deedaa6",
          "sha256": "fab4d2241a16a0ffeff129b4125851f105fa4d80882cc0d2101c25b7b1fb29c6",
          "sha1": "06d4784649bb7cd6e35323c30cc66a6d36236e1a",
          "md5": "c62121c77b8c4943356269f96ba7a905"
        }
      ]
    }
  ]
}
