{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.4.5.jar",
          "url": "common-1.4.5.jar",
          "size": 16455,
          "sha512": "e28d7fa94fc1b7b882d4a9a74265536e466a77aa44c885573f0620d20208eac28747c90ead23402c5aae902762f4d780494668227d77d91ab04c0662b30f89c9",
          "sha256": "7fd371e5ef9b80e907872a687b832619e6781d2f9a3f10ee7b00407ed4968185",
          "sha1": "975b431d58916693c26acee70c0f264c4013e2a7",
          "md5": "67e6d59f5e3ab16f4d40df84a024baac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "tools",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "7.0.0.202409031743-r"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.4.5.jar",
          "url": "common-1.4.5.jar",
          "size": 16455,
          "sha512": "e28d7fa94fc1b7b882d4a9a74265536e466a77aa44c885573f0620d20208eac28747c90ead23402c5aae902762f4d780494668227d77d91ab04c0662b30f89c9",
          "sha256": "7fd371e5ef9b80e907872a687b832619e6781d2f9a3f10ee7b00407ed4968185",
          "sha1": "975b431d58916693c26acee70c0f264c4013e2a7",
          "md5": "67e6d59f5e3ab16f4d40df84a024baac"
        }
      ]
    }
  ]
}
