{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.4.5.jar",
          "url": "common-1.4.5.jar",
          "size": 16454,
          "sha512": "0072ae5117d84b206242a2e3763ee091088b4d245925e267036cf438b0c1872c1a98c382deb5276a256c29a91134ee079b5e83b4c8288a49a83f5dd48bc5e0fd",
          "sha256": "63af238a40f62278a62d3ac62007c916365c2fad2638cbf70b8f0b8cef8411cc",
          "sha1": "7f812de0c52b7bb19253937845648c72c8b83359",
          "md5": "a641f728520f9bcad7af9a90a7a2d20b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "tools",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "7.0.0.202409031743-r"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.4.5.jar",
          "url": "common-1.4.5.jar",
          "size": 16454,
          "sha512": "0072ae5117d84b206242a2e3763ee091088b4d245925e267036cf438b0c1872c1a98c382deb5276a256c29a91134ee079b5e83b4c8288a49a83f5dd48bc5e0fd",
          "sha256": "63af238a40f62278a62d3ac62007c916365c2fad2638cbf70b8f0b8cef8411cc",
          "sha1": "7f812de0c52b7bb19253937845648c72c8b83359",
          "md5": "a641f728520f9bcad7af9a90a7a2d20b"
        }
      ]
    }
  ]
}
