{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.3.0.jar",
          "url": "common-1.3.0.jar",
          "size": 9256,
          "sha512": "8e8ef851ac1fa2e6d6747f9aeb168b735bc107c04260c0da9bea37453bbeaa3a5dc7a6813d4d7635fbe82ff15e20799c3e68a4f2a832f87dd17641acb520c503",
          "sha256": "c5105fbd3bcaf74689d5a8081404c7ebbc01206d4abb7ac3e7faecdb5b6c06dd",
          "sha1": "657251e6bb8bd1a0d4ff10e287d65b4582a2183f",
          "md5": "10fb29ca4c745b3828a00bc7db2d24c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.3.0.jar",
          "url": "common-1.3.0.jar",
          "size": 9256,
          "sha512": "8e8ef851ac1fa2e6d6747f9aeb168b735bc107c04260c0da9bea37453bbeaa3a5dc7a6813d4d7635fbe82ff15e20799c3e68a4f2a832f87dd17641acb520c503",
          "sha256": "c5105fbd3bcaf74689d5a8081404c7ebbc01206d4abb7ac3e7faecdb5b6c06dd",
          "sha1": "657251e6bb8bd1a0d4ff10e287d65b4582a2183f",
          "md5": "10fb29ca4c745b3828a00bc7db2d24c8"
        }
      ]
    }
  ]
}
