{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.3.0.jar",
          "url": "common-1.3.0.jar",
          "size": 9217,
          "sha512": "f87937d4d39d0d6cdba47344b885464d66e84ee072212943bf198c895da67431b7f51b00c2a65597ea220f2fc0590f707dfbb3258fa805b1e16570275ac69c72",
          "sha256": "976e1ea128d71ea4ba70dac4701df3cea6a9b5f2aedefc4f8b833ac322ad0e6c",
          "sha1": "424d3f67d447703d647bbe84b1b9b00f781fd396",
          "md5": "7ff00afe5dd6f78c8e7e2bae88274ed4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.3.0.jar",
          "url": "common-1.3.0.jar",
          "size": 9217,
          "sha512": "f87937d4d39d0d6cdba47344b885464d66e84ee072212943bf198c895da67431b7f51b00c2a65597ea220f2fc0590f707dfbb3258fa805b1e16570275ac69c72",
          "sha256": "976e1ea128d71ea4ba70dac4701df3cea6a9b5f2aedefc4f8b833ac322ad0e6c",
          "sha1": "424d3f67d447703d647bbe84b1b9b00f781fd396",
          "md5": "7ff00afe5dd6f78c8e7e2bae88274ed4"
        }
      ]
    }
  ]
}
