{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.3.0.jar",
          "url": "common-1.3.0.jar",
          "size": 9147,
          "sha512": "60cc4ba24b73883405c7ab19f6efc4ab50e5d6056c20c9f5e276f8d6a55df419e19ced5c2566f5b29d3a4a16557c04d25eabe8d989b5d3e860ac9d94dbcca7dc",
          "sha256": "a24bd567963d2459321de87b792bb0e74d4b3359602a85805ecfc805af50b7db",
          "sha1": "3b94ed93a79cc36d44d7dd74b905bf1d87925a7b",
          "md5": "bc4cec1ef411b56fa53f9fe216f21fdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.3.0.jar",
          "url": "common-1.3.0.jar",
          "size": 9147,
          "sha512": "60cc4ba24b73883405c7ab19f6efc4ab50e5d6056c20c9f5e276f8d6a55df419e19ced5c2566f5b29d3a4a16557c04d25eabe8d989b5d3e860ac9d94dbcca7dc",
          "sha256": "a24bd567963d2459321de87b792bb0e74d4b3359602a85805ecfc805af50b7db",
          "sha1": "3b94ed93a79cc36d44d7dd74b905bf1d87925a7b",
          "md5": "bc4cec1ef411b56fa53f9fe216f21fdb"
        }
      ]
    }
  ]
}
