{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.4.3.jar",
          "url": "jupyter-plugin-1.4.3.jar",
          "size": 15698,
          "sha512": "7e64bf2caebcfdd3250e2487cda6593359af3057dd3c7e0dbb8a09884202c167e9867419a1b2179cfc2f8caf6a4f15dff9c9dd787034fbbc48cc969255b0d992",
          "sha256": "2045cad1fd47ddcd78c97ac8b82bf591c899c5c67ac550ec79030f7c66d125b9",
          "sha1": "fe8177f7e29abc3f24f76cf772f2e5d61cabdaca",
          "md5": "c0b9b7d0bba145a7992722d5b49e06be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.4.3.jar",
          "url": "jupyter-plugin-1.4.3.jar",
          "size": 15698,
          "sha512": "7e64bf2caebcfdd3250e2487cda6593359af3057dd3c7e0dbb8a09884202c167e9867419a1b2179cfc2f8caf6a4f15dff9c9dd787034fbbc48cc969255b0d992",
          "sha256": "2045cad1fd47ddcd78c97ac8b82bf591c899c5c67ac550ec79030f7c66d125b9",
          "sha1": "fe8177f7e29abc3f24f76cf772f2e5d61cabdaca",
          "md5": "c0b9b7d0bba145a7992722d5b49e06be"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.0"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.4.3-all.jar",
          "url": "jupyter-plugin-1.4.3-all.jar",
          "size": 2308642,
          "sha512": "840fe390669c8e75756425d168fd0d873021608ca73504bed994eeab15054e39d9615087f6366752e6071da4e378dca3e59c9141df1454e81f5c061c9e80b001",
          "sha256": "6465fc7c5bc5f1b1e5902ea4267d0392d873f7816e452326d122ceef46ae6221",
          "sha1": "37a7c46e367d1cc4e3e1e4207ff62597f005625c",
          "md5": "ff9c20f0241c5dda7f6841cc179b4911"
        }
      ]
    }
  ]
}
