{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.4.3.jar",
          "url": "jupyter-plugin-1.4.3.jar",
          "size": 15503,
          "sha512": "d7e316257a8d7bec36a08177c8abcd679a194c02092697691b6dd193cee7481887b7b6636636f99fdff6c0cd825048a3413660aa860faee03cc974d5e413cd55",
          "sha256": "00d1f9539e63f51c20eb536eee89556e32d2d214a86f366245b6a65ad141f830",
          "sha1": "3de65e91caaa496ec576e6483f408ab7fdad9e80",
          "md5": "5f9072701cdb8ef4a4ab9d9fb4643711"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.0"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.4.3.jar",
          "url": "jupyter-plugin-1.4.3.jar",
          "size": 15503,
          "sha512": "d7e316257a8d7bec36a08177c8abcd679a194c02092697691b6dd193cee7481887b7b6636636f99fdff6c0cd825048a3413660aa860faee03cc974d5e413cd55",
          "sha256": "00d1f9539e63f51c20eb536eee89556e32d2d214a86f366245b6a65ad141f830",
          "sha1": "3de65e91caaa496ec576e6483f408ab7fdad9e80",
          "md5": "5f9072701cdb8ef4a4ab9d9fb4643711"
        }
      ]
    }
  ]
}
