{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.4.3-empty.jar",
          "url": "jupyter-plugin-1.4.3-empty.jar",
          "size": 15698,
          "sha512": "d48823c9008ddcc0b5c5f8ec05f0e100a0aea47777d384fbd790e182351a4378b951cc844638912ebb7aaeacdc21df1112a6dca439393b86c6b05a361d609dbd",
          "sha256": "57a01edda91faec38999e7599177ce3bc4922e0dbddbcedd6f3ce4d4b50af75c",
          "sha1": "4a31d8130e409b2ce572000eb1c8b6f3aee45d98",
          "md5": "5ecf00e812497eb12e7bc8752e06ec51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.0"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.4.3-empty.jar",
          "url": "jupyter-plugin-1.4.3-empty.jar",
          "size": 15698,
          "sha512": "d48823c9008ddcc0b5c5f8ec05f0e100a0aea47777d384fbd790e182351a4378b951cc844638912ebb7aaeacdc21df1112a6dca439393b86c6b05a361d609dbd",
          "sha256": "57a01edda91faec38999e7599177ce3bc4922e0dbddbcedd6f3ce4d4b50af75c",
          "sha1": "4a31d8130e409b2ce572000eb1c8b6f3aee45d98",
          "md5": "5ecf00e812497eb12e7bc8752e06ec51"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.4.3.jar",
          "url": "jupyter-plugin-1.4.3.jar",
          "size": 2691591,
          "sha512": "047b91a4465c01f1ebb6476c466b5867a10fcbe21eeb614cfe3b0b9b02a29b8293142980e235b30f5f6099390a0e5e835966afde187f0dfe909d0cd19b583bc5",
          "sha256": "1c6d950fe625b5c16185f7516e003e574e627102687c5d67ebee681c3df3322a",
          "sha1": "8ba920d17c2b7097db82bbaf28a345d9bde8cecf",
          "md5": "6e8bebe71f842445f9a3761c7cac6226"
        }
      ]
    }
  ]
}
