{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "ocean-committer",
    "version": "1.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ocean-committer-1.2.8.jar",
          "url": "ocean-committer-1.2.8.jar",
          "size": 950656,
          "sha512": "10c93852f9e6aa54b028802e894d53e3122427ef11c16831be87e254bc9773d6b9377d5a62d98107ce77bc97ea374603304260a9e510033d65be12dc4e3c9be0",
          "sha256": "d1b3cb667644268ad063dbd6c9718dab61569d3bb1bebf0e02ea3fac2ec9268e",
          "sha1": "ac375bff427ad9f003e381e12f826b56849d3c4c",
          "md5": "893d3ee5a51698626314c0fb995e03a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-hadoop-cloud_2.12",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.apache.hadoop",
          "module": "hadoop-hdfs",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.apache.hadoop",
          "module": "hadoop-common",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.apache.hadoop",
          "module": "hadoop-mapreduce-client-core",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk",
          "version": {
            "requires": "1.12.262"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-java-sdk-bundle",
          "version": {
            "requires": "1.12.262"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "s3",
          "version": {
            "requires": "2.24.12"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "core",
          "version": {
            "requires": "2.24.12"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "aws-core",
          "version": {
            "requires": "2.24.12"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "s3-transfer-manager",
          "version": {
            "requires": "2.24.12"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "apache-client",
          "version": {
            "requires": "2.24.12"
          }
        },
        {
          "group": "software.amazon.awssdk",
          "module": "bundle",
          "version": {
            "requires": "2.24.12"
          }
        }
      ],
      "files": [
        {
          "name": "ocean-committer-1.2.8.jar",
          "url": "ocean-committer-1.2.8.jar",
          "size": 950656,
          "sha512": "10c93852f9e6aa54b028802e894d53e3122427ef11c16831be87e254bc9773d6b9377d5a62d98107ce77bc97ea374603304260a9e510033d65be12dc4e3c9be0",
          "sha256": "d1b3cb667644268ad063dbd6c9718dab61569d3bb1bebf0e02ea3fac2ec9268e",
          "sha1": "ac375bff427ad9f003e381e12f826b56849d3c4c",
          "md5": "893d3ee5a51698626314c0fb995e03a2"
        }
      ]
    }
  ]
}
