{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "tools",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-1.5.0-empty.jar",
          "url": "tools-1.5.0-empty.jar",
          "size": 2549,
          "sha512": "99831bc01048d0c93c193164c8481d8e60e4b75a4487556c266fd449623d3cecb25517471b1abbf314daca0648d99b3b21249309bb891fbd277c4108dac3852d",
          "sha256": "7360a9fa9452a18458d40396b095ddc4c663f3a637ab55f27ca19ecf2a68107f",
          "sha1": "2c1fbdf4e3e190e25028fd1e6f53dbadb5b4d0b0",
          "md5": "1f81e3f200fa8c998e425c1c0b79f4fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.5.0-empty.jar",
          "url": "tools-1.5.0-empty.jar",
          "size": 2549,
          "sha512": "99831bc01048d0c93c193164c8481d8e60e4b75a4487556c266fd449623d3cecb25517471b1abbf314daca0648d99b3b21249309bb891fbd277c4108dac3852d",
          "sha256": "7360a9fa9452a18458d40396b095ddc4c663f3a637ab55f27ca19ecf2a68107f",
          "sha1": "2c1fbdf4e3e190e25028fd1e6f53dbadb5b4d0b0",
          "md5": "1f81e3f200fa8c998e425c1c0b79f4fa"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-1.5.0.jar",
          "url": "tools-1.5.0.jar",
          "size": 2672954,
          "sha512": "cdfd77cbbe4e697d4e59d2224ce1895f245804738e4391487c8f3fc0b2036d8f4cf0b070240a23def6e924b6c9885d2808478871224ef018a712b56f8dd4b617",
          "sha256": "a58c23eb453506bb29216aeca57f58180642cb4bfdcb81dfebc197e230968157",
          "sha1": "d97469a14b58685e829d2029cabd190b5dae44c6",
          "md5": "a32793b1515cd4b323fcf7203877a130"
        }
      ]
    }
  ]
}
