{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "tools",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-1.5.0-empty.jar",
          "url": "tools-1.5.0-empty.jar",
          "size": 2549,
          "sha512": "99831bc01048d0c93c193164c8481d8e60e4b75a4487556c266fd449623d3cecb25517471b1abbf314daca0648d99b3b21249309bb891fbd277c4108dac3852d",
          "sha256": "7360a9fa9452a18458d40396b095ddc4c663f3a637ab55f27ca19ecf2a68107f",
          "sha1": "2c1fbdf4e3e190e25028fd1e6f53dbadb5b4d0b0",
          "md5": "1f81e3f200fa8c998e425c1c0b79f4fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.5.0-empty.jar",
          "url": "tools-1.5.0-empty.jar",
          "size": 2549,
          "sha512": "99831bc01048d0c93c193164c8481d8e60e4b75a4487556c266fd449623d3cecb25517471b1abbf314daca0648d99b3b21249309bb891fbd277c4108dac3852d",
          "sha256": "7360a9fa9452a18458d40396b095ddc4c663f3a637ab55f27ca19ecf2a68107f",
          "sha1": "2c1fbdf4e3e190e25028fd1e6f53dbadb5b4d0b0",
          "md5": "1f81e3f200fa8c998e425c1c0b79f4fa"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-1.5.0.jar",
          "url": "tools-1.5.0.jar",
          "size": 2672954,
          "sha512": "5ed84d18abeea9867fc6c0cde764d3bfb4dfdc0680a23fdae8a4ac5905841a15c8caa9a4ada1d086f6bfa7f70f9c4c9b707d29e0729c5010c33717f982ee95c7",
          "sha256": "de8cd30495843ba60baff512b27425ba69c9eb23eab46a410a7a04fe9d6e1041",
          "sha1": "7f759d1cc439117951763d20c3da09bede132614",
          "md5": "68d87a9713cc5409cce4777f0b44962b"
        }
      ]
    }
  ]
}
