{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "vscode-plugin",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vscode-plugin-1.4.1.jar",
          "url": "vscode-plugin-1.4.1.jar",
          "size": 19619,
          "sha512": "465da117e1ffc214b6465b50fb2e011f753ace543e9c407ea085604a081b186f3db27b5b9e6b0d6da1144a1daddfa5dfa860203d78655a16c8da32c37050a4f4",
          "sha256": "3d2c7bc5f710a035fd1612fa2b701cc0bcffe47722befef4d94c1985588920cf",
          "sha1": "a7c6beb7ad506a629e3ded6cac4e18ca646fdcd3",
          "md5": "1df0bd57955a04108829e1b65f19acdd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        }
      ],
      "files": [
        {
          "name": "vscode-plugin-1.4.1.jar",
          "url": "vscode-plugin-1.4.1.jar",
          "size": 19619,
          "sha512": "465da117e1ffc214b6465b50fb2e011f753ace543e9c407ea085604a081b186f3db27b5b9e6b0d6da1144a1daddfa5dfa860203d78655a16c8da32c37050a4f4",
          "sha256": "3d2c7bc5f710a035fd1612fa2b701cc0bcffe47722befef4d94c1985588920cf",
          "sha1": "a7c6beb7ad506a629e3ded6cac4e18ca646fdcd3",
          "md5": "1df0bd57955a04108829e1b65f19acdd"
        }
      ]
    }
  ]
}
