{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "spark-cluster",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spark-cluster-1.4.4.jar",
          "url": "spark-cluster-1.4.4.jar",
          "size": 6810,
          "sha512": "c4b74353efe75202753ebff33dc43a6ddde935bc9ad3f2ad6793d1f3182b9589f5fdf0ba1ab40b4793e751ca94fea5f03875d42a6ba294dabe3646aad8ab2cfb",
          "sha256": "47ce9e85bdc83c4910f0a27e46b94d9427d129489db3655132d1b1629e432add",
          "sha1": "a991bf452ebd0eb5e74c09be1d001b849020bfb3",
          "md5": "4dcaea32c86783ca9412160361025f43"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.13",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.13",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "spark-cluster-1.4.4.jar",
          "url": "spark-cluster-1.4.4.jar",
          "size": 6810,
          "sha512": "c4b74353efe75202753ebff33dc43a6ddde935bc9ad3f2ad6793d1f3182b9589f5fdf0ba1ab40b4793e751ca94fea5f03875d42a6ba294dabe3646aad8ab2cfb",
          "sha256": "47ce9e85bdc83c4910f0a27e46b94d9427d129489db3655132d1b1629e432add",
          "sha1": "a991bf452ebd0eb5e74c09be1d001b849020bfb3",
          "md5": "4dcaea32c86783ca9412160361025f43"
        }
      ]
    }
  ]
}
