{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "spark-cluster",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spark-cluster-1.4.4.jar",
          "url": "spark-cluster-1.4.4.jar",
          "size": 2388,
          "sha512": "e3ad3107c0966833d4e2923960d3e17a4ad8b6d0d3b9be6306012c71814104ff10b0f4bbfb52a04e6e9369fe479c996177e9cb97dbe75d0d2f4e8d3adde676da",
          "sha256": "1b62d569da324fcef214ed79484d8794297d43dcd8ec35196be7433b4e88b29b",
          "sha1": "565977968ab2d05e3af87b9829356803b71bacc4",
          "md5": "5a3f5abc9f071460b7b1e392e28b4506"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "spark-cluster-1.4.4.jar",
          "url": "spark-cluster-1.4.4.jar",
          "size": 2388,
          "sha512": "e3ad3107c0966833d4e2923960d3e17a4ad8b6d0d3b9be6306012c71814104ff10b0f4bbfb52a04e6e9369fe479c996177e9cb97dbe75d0d2f4e8d3adde676da",
          "sha256": "1b62d569da324fcef214ed79484d8794297d43dcd8ec35196be7433b4e88b29b",
          "sha1": "565977968ab2d05e3af87b9829356803b71bacc4",
          "md5": "5a3f5abc9f071460b7b1e392e28b4506"
        }
      ]
    }
  ]
}
