{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "spark-cluster",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spark-cluster-1.4.4.jar",
          "url": "spark-cluster-1.4.4.jar",
          "size": 6517,
          "sha512": "7f3ea4a1f2ed91e471c7542cc3db94f5889a2ed193165bacb05fca768557e372650e410a791b1710246891a36f15186a7d33502bf00826e4f5c643566d9ee879",
          "sha256": "64585b3ee2f7a5928e422cb938e65a870ba7ce9f16f52ced7d233e17877b8a62",
          "sha1": "5d5b428cd0be950851c6044537b8a87a3539c505",
          "md5": "59d3a94d60c97dcc99df55f7a1d6a2af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.13",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.13",
          "version": {
            "requires": "3.5.3"
          }
        }
      ],
      "files": [
        {
          "name": "spark-cluster-1.4.4.jar",
          "url": "spark-cluster-1.4.4.jar",
          "size": 6517,
          "sha512": "7f3ea4a1f2ed91e471c7542cc3db94f5889a2ed193165bacb05fca768557e372650e410a791b1710246891a36f15186a7d33502bf00826e4f5c643566d9ee879",
          "sha256": "64585b3ee2f7a5928e422cb938e65a870ba7ce9f16f52ced7d233e17877b8a62",
          "sha1": "5d5b428cd0be950851c6044537b8a87a3539c505",
          "md5": "59d3a94d60c97dcc99df55f7a1d6a2af"
        }
      ]
    }
  ]
}
