{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.4.4.jar",
          "url": "common-1.4.4.jar",
          "size": 10115,
          "sha512": "34c0afd01ff8d575c66ff6bf775eca0acad5dd4390dcb0a5a001e63d1d9adbfa298cbb7c0bbfe00c4ddccf1902f0810cc47f8aab4cd286d273211edc28e78df5",
          "sha256": "3e0198cec76e21862ecc0b2b2e00840be2935edfd1b02ddbaa137202d1809486",
          "sha1": "d3752827bf383d12fd7e109027c45e20609043ea",
          "md5": "092afae55523f2eb78f131fbe67bcd86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.4.4.jar",
          "url": "common-1.4.4.jar",
          "size": 10115,
          "sha512": "34c0afd01ff8d575c66ff6bf775eca0acad5dd4390dcb0a5a001e63d1d9adbfa298cbb7c0bbfe00c4ddccf1902f0810cc47f8aab4cd286d273211edc28e78df5",
          "sha256": "3e0198cec76e21862ecc0b2b2e00840be2935edfd1b02ddbaa137202d1809486",
          "sha1": "d3752827bf383d12fd7e109027c45e20609043ea",
          "md5": "092afae55523f2eb78f131fbe67bcd86"
        }
      ]
    }
  ]
}
