{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.4.3.jar",
          "url": "common-1.4.3.jar",
          "size": 9917,
          "sha512": "3cb5524335dd5e77114aaa2078effceb35e5839d6c911ae26aa48ce10012ab4730f032ed71c90be7d2871387fefcd93e93f675f41869fb1af3896c45b7b3c491",
          "sha256": "587651c69841c9051a7e6b01d28d16e0488e508a25f99af23115a8b9944cc75b",
          "sha1": "094e7de6fa3cc1f07dbf16498d7fc30004a345c6",
          "md5": "0e20440992bf55b2f31fe67520da002f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.4.3.jar",
          "url": "common-1.4.3.jar",
          "size": 9917,
          "sha512": "3cb5524335dd5e77114aaa2078effceb35e5839d6c911ae26aa48ce10012ab4730f032ed71c90be7d2871387fefcd93e93f675f41869fb1af3896c45b7b3c491",
          "sha256": "587651c69841c9051a7e6b01d28d16e0488e508a25f99af23115a8b9944cc75b",
          "sha1": "094e7de6fa3cc1f07dbf16498d7fc30004a345c6",
          "md5": "0e20440992bf55b2f31fe67520da002f"
        }
      ]
    }
  ]
}
