{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.4.3.jar",
          "url": "common-1.4.3.jar",
          "size": 10001,
          "sha512": "df7c4ddd5ded3338203ef7c9a5b37befcd9b56cbeedb6fdf053cbf394df0620221488a4710540c2b1cd9adf5c3d92ee38973fabb1c17c1168cec573953334f5b",
          "sha256": "0d72c3205229262847325df515da9441d16be456bbd5650bfd084496418199b1",
          "sha1": "94d4a24e83612b524f538e7e992c3639eb3f4865",
          "md5": "2defacca822aa9aa30d0734947f61ca5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.4.3.jar",
          "url": "common-1.4.3.jar",
          "size": 10001,
          "sha512": "df7c4ddd5ded3338203ef7c9a5b37befcd9b56cbeedb6fdf053cbf394df0620221488a4710540c2b1cd9adf5c3d92ee38973fabb1c17c1168cec573953334f5b",
          "sha256": "0d72c3205229262847325df515da9441d16be456bbd5650bfd084496418199b1",
          "sha1": "94d4a24e83612b524f538e7e992c3639eb3f4865",
          "md5": "2defacca822aa9aa30d0734947f61ca5"
        }
      ]
    }
  ]
}
