{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "vscode-plugin",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vscode-plugin-1.4.0.jar",
          "url": "vscode-plugin-1.4.0.jar",
          "size": 19588,
          "sha512": "8e2c02fea0843560b907866db9229bfe9f53660b29c92ea233c6c959b85a6a333625bf89edab4fbd2b1921fc93af10504896a4603cc9b8530427748c8ddda44d",
          "sha256": "131bf30f8fc615a02d0a6e6b27883ac728df5babce3183f70a120c6b31d58103",
          "sha1": "b76c762855d6e4e87bbd861462254ce7b95f494d",
          "md5": "a8cb4e7821dc4e77bb8826f83e33801f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        }
      ],
      "files": [
        {
          "name": "vscode-plugin-1.4.0.jar",
          "url": "vscode-plugin-1.4.0.jar",
          "size": 19588,
          "sha512": "8e2c02fea0843560b907866db9229bfe9f53660b29c92ea233c6c959b85a6a333625bf89edab4fbd2b1921fc93af10504896a4603cc9b8530427748c8ddda44d",
          "sha256": "131bf30f8fc615a02d0a6e6b27883ac728df5babce3183f70a120c6b31d58103",
          "sha1": "b76c762855d6e4e87bbd861462254ce7b95f494d",
          "md5": "a8cb4e7821dc4e77bb8826f83e33801f"
        }
      ]
    }
  ]
}
