{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.0.0.jar",
          "url": "jupyter-plugin-1.0.0.jar",
          "size": 10882,
          "sha512": "bf8f421c29ae2918499b20a6e778fb4a81fd3ae79bf4a7cdf3f22d72126ef4284cadf4d08132f20a3c925a614e2993a8c9adaccb75cb2ec64ee7752e33d464a1",
          "sha256": "312de0bbc8440386c5fee92e0f675e4f2e40cf63dd78d07c140bbf232b27289b",
          "sha1": "96c5b82254601303eb964089eda29f1766a291a0",
          "md5": "6538feb484a92505b0732616b90a33b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "6.7.2"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-client-api",
          "version": {
            "requires": "6.7.2"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-httpclient-okhttp",
          "version": {
            "requires": "6.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.0.0.jar",
          "url": "jupyter-plugin-1.0.0.jar",
          "size": 10882,
          "sha512": "bf8f421c29ae2918499b20a6e778fb4a81fd3ae79bf4a7cdf3f22d72126ef4284cadf4d08132f20a3c925a614e2993a8c9adaccb75cb2ec64ee7752e33d464a1",
          "sha256": "312de0bbc8440386c5fee92e0f675e4f2e40cf63dd78d07c140bbf232b27289b",
          "sha1": "96c5b82254601303eb964089eda29f1766a291a0",
          "md5": "6538feb484a92505b0732616b90a33b2"
        }
      ]
    }
  ]
}
