{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.0.0.jar",
          "url": "jupyter-plugin-1.0.0.jar",
          "size": 11712,
          "sha512": "8c29676e36eeb2c5e702bd9c12c1e57b5a038cf1d602fb316d73672f0693ed77f24f42d73d9faa82cd674da3fd89f13a6c214982ec37261a29c491d0164ac347",
          "sha256": "0badabb373b30dfafa0d9e0e8b9c40c4d7428c454cdef4b87e08fa9dcca10fc3",
          "sha1": "8fc221748af0fc1873aaa54415c2e7fff561c886",
          "md5": "c1f447fd7353ae98608d5fa974de4626"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "6.7.2"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-client-api",
          "version": {
            "requires": "6.7.2"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-httpclient-okhttp",
          "version": {
            "requires": "6.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.0.0.jar",
          "url": "jupyter-plugin-1.0.0.jar",
          "size": 11712,
          "sha512": "8c29676e36eeb2c5e702bd9c12c1e57b5a038cf1d602fb316d73672f0693ed77f24f42d73d9faa82cd674da3fd89f13a6c214982ec37261a29c491d0164ac347",
          "sha256": "0badabb373b30dfafa0d9e0e8b9c40c4d7428c454cdef4b87e08fa9dcca10fc3",
          "sha1": "8fc221748af0fc1873aaa54415c2e7fff561c886",
          "md5": "c1f447fd7353ae98608d5fa974de4626"
        }
      ]
    }
  ]
}
