{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.0.0.jar",
          "url": "jupyter-plugin-1.0.0.jar",
          "size": 11712,
          "sha512": "a6e269b1e347311457a20cbaae4ec54121a626eafd5e5c6667294d535805249731b3f5f27da399391a651f83b9d5bf0e956331805132c0c8dc76a503312eaa95",
          "sha256": "5d52f6fdf5975ebf407fa2f027c450df1602b681390b2d0a6f17495fb667c932",
          "sha1": "c8da103b572024216db8dda9942ec4ac7d756696",
          "md5": "1f6001dc914cd639de32528a18a568d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "6.7.2"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-client-api",
          "version": {
            "requires": "6.7.2"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-httpclient-okhttp",
          "version": {
            "requires": "6.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.0.0.jar",
          "url": "jupyter-plugin-1.0.0.jar",
          "size": 11712,
          "sha512": "a6e269b1e347311457a20cbaae4ec54121a626eafd5e5c6667294d535805249731b3f5f27da399391a651f83b9d5bf0e956331805132c0c8dc76a503312eaa95",
          "sha256": "5d52f6fdf5975ebf407fa2f027c450df1602b681390b2d0a6f17495fb667c932",
          "sha1": "c8da103b572024216db8dda9942ec4ac7d756696",
          "md5": "1f6001dc914cd639de32528a18a568d8"
        }
      ]
    }
  ]
}
