{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0.0.jar",
          "url": "common-1.0.0.jar",
          "size": 8555,
          "sha512": "beea7fc9d66def384a6f05556676c4cca698219aa6a1ebff9e72930c4f353973e979195a61c865cd3ec1e092471ed2da232b000aaa70deccff570c717b88c14d",
          "sha256": "bb47487e8647dbfd69c03377b5da6ab55c26731b38bd61217b16246e4d86cc3e",
          "sha1": "e8cc18a69812ee90e0e8af1979db6d014c095969",
          "md5": "682cfcfb8138a18440980824b7982c56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0.jar",
          "url": "common-1.0.0.jar",
          "size": 8555,
          "sha512": "beea7fc9d66def384a6f05556676c4cca698219aa6a1ebff9e72930c4f353973e979195a61c865cd3ec1e092471ed2da232b000aaa70deccff570c717b88c14d",
          "sha256": "bb47487e8647dbfd69c03377b5da6ab55c26731b38bd61217b16246e4d86cc3e",
          "sha1": "e8cc18a69812ee90e0e8af1979db6d014c095969",
          "md5": "682cfcfb8138a18440980824b7982c56"
        }
      ]
    }
  ]
}
