{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0.0.jar",
          "url": "common-1.0.0.jar",
          "size": 7747,
          "sha512": "5e35aa781a7a5ec5de1fe281f1c861417446eb2c28a796474b6017c3be92429ab905e103ac4823804b69a86f6a78b33719e49128a35fe8436816fe11fd15c9bc",
          "sha256": "a10ac9a38e3f3d3e85841e97b89ddd363dbe0dc82248556a3a44dbd6190d040f",
          "sha1": "d75d75947f78f431fc35ad3ed31aa0d11303be3f",
          "md5": "3f93bac1ca54c056f0941efd7a85d8f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0.jar",
          "url": "common-1.0.0.jar",
          "size": 7747,
          "sha512": "5e35aa781a7a5ec5de1fe281f1c861417446eb2c28a796474b6017c3be92429ab905e103ac4823804b69a86f6a78b33719e49128a35fe8436816fe11fd15c9bc",
          "sha256": "a10ac9a38e3f3d3e85841e97b89ddd363dbe0dc82248556a3a44dbd6190d040f",
          "sha1": "d75d75947f78f431fc35ad3ed31aa0d11303be3f",
          "md5": "3f93bac1ca54c056f0941efd7a85d8f3"
        }
      ]
    }
  ]
}
