{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0.0.jar",
          "url": "common-1.0.0.jar",
          "size": 8147,
          "sha512": "1dce9d922d51d10d618d390dc260cc139bc4a0cead5d0ddf0ed5e14110e33c6b3f6453e1349dfe2e231afa97861536386479bc075ee75268f95964b974a8f2b3",
          "sha256": "b0eac6b9b3302c09c9e22cc79ad421d3ffe2a5a8f1012485d5036b07161d7307",
          "sha1": "c66340d4ea032ffffa6413a78ae0db86b23dbd5f",
          "md5": "2408716b1ee3dd40666212e7035d4591"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.0.jar",
          "url": "common-1.0.0.jar",
          "size": 8147,
          "sha512": "1dce9d922d51d10d618d390dc260cc139bc4a0cead5d0ddf0ed5e14110e33c6b3f6453e1349dfe2e231afa97861536386479bc075ee75268f95964b974a8f2b3",
          "sha256": "b0eac6b9b3302c09c9e22cc79ad421d3ffe2a5a8f1012485d5036b07161d7307",
          "sha1": "c66340d4ea032ffffa6413a78ae0db86b23dbd5f",
          "md5": "2408716b1ee3dd40666212e7035d4591"
        }
      ]
    }
  ]
}
