{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "ai",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ai-1.4.0.jar",
          "url": "ai-1.4.0.jar",
          "size": 5461,
          "sha512": "3dac22ccdff7b572542f1ed66d275530356096400ffa8cfce457c0fa0dafd7996b299fdcd298582b20658b5e0b153afafa7dbc4e011d4130d61b723887a97d6c",
          "sha256": "a0b747d8731d1945a9915a7727a00d6069f65ec05a0c13045ba12fd6c17f0579",
          "sha1": "17110618a314d83fef4a90349943cbbe2b43d81a",
          "md5": "1a67be94f3c0b418ff06f21e9f92b551"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ai-1.4.0.jar",
          "url": "ai-1.4.0.jar",
          "size": 5461,
          "sha512": "3dac22ccdff7b572542f1ed66d275530356096400ffa8cfce457c0fa0dafd7996b299fdcd298582b20658b5e0b153afafa7dbc4e011d4130d61b723887a97d6c",
          "sha256": "a0b747d8731d1945a9915a7727a00d6069f65ec05a0c13045ba12fd6c17f0579",
          "sha1": "17110618a314d83fef4a90349943cbbe2b43d81a",
          "md5": "1a67be94f3c0b418ff06f21e9f92b551"
        }
      ]
    }
  ]
}
