{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "ai",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ai-1.4.0.jar",
          "url": "ai-1.4.0.jar",
          "size": 3955,
          "sha512": "d5c860c384a840258ee1450590f14a3004a7d2f984b4d9169651a5928178bc4cefcc43364b5ebe3ae589e3e4506a95dac6137fd11e589d3ff9d7a943528f167c",
          "sha256": "9b8086271dff04a751627f9d3573f633cafad51088e87a594b803948f2807192",
          "sha1": "5ac0d8836e279be26cd397c5a646fef338b32fba",
          "md5": "5bfb75cca6d29fd549c41a734d867d84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ai-1.4.0.jar",
          "url": "ai-1.4.0.jar",
          "size": 3955,
          "sha512": "d5c860c384a840258ee1450590f14a3004a7d2f984b4d9169651a5928178bc4cefcc43364b5ebe3ae589e3e4506a95dac6137fd11e589d3ff9d7a943528f167c",
          "sha256": "9b8086271dff04a751627f9d3573f633cafad51088e87a594b803948f2807192",
          "sha1": "5ac0d8836e279be26cd397c5a646fef338b32fba",
          "md5": "5bfb75cca6d29fd549c41a734d867d84"
        }
      ]
    }
  ]
}
