{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "ai",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ai-1.4.0.jar",
          "url": "ai-1.4.0.jar",
          "size": 3797,
          "sha512": "e90b54748a7386ce4364dd029e5eab0550b88afd86e53c36a282f775b7b29d8efd4971e275a3b58012496a389d696edc19cfbdc0f2d3921fc8a36f08088c064d",
          "sha256": "39ad071464e48dc0e947f4c71389a8904d09209dd1710b1ce6842d81770d7e94",
          "sha1": "482bb0e422baf3d32ba28ba319b8d524495109f2",
          "md5": "5d56c3b8ac4c21edd9f1e36ef841fe15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.5.1"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ai-1.4.0.jar",
          "url": "ai-1.4.0.jar",
          "size": 3797,
          "sha512": "e90b54748a7386ce4364dd029e5eab0550b88afd86e53c36a282f775b7b29d8efd4971e275a3b58012496a389d696edc19cfbdc0f2d3921fc8a36f08088c064d",
          "sha256": "39ad071464e48dc0e947f4c71389a8904d09209dd1710b1ce6842d81770d7e94",
          "sha1": "482bb0e422baf3d32ba28ba319b8d524495109f2",
          "md5": "5d56c3b8ac4c21edd9f1e36ef841fe15"
        }
      ]
    }
  ]
}
