{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.4.1.jar",
          "url": "common-1.4.1.jar",
          "size": 10110,
          "sha512": "fa7507f565b502576128b53756a904a1c31c3af83c064c3db9bacebb51a5eee967a2cb3193b305946427ffea84ce417c6c78e9eb68063d14c89d17f07b12ae93",
          "sha256": "8f72f37bbf20e6a845c86f98d1211edff45eeabf15f7f45b0b276ac02d503ce1",
          "sha1": "71785ceb37efdfb8c1e078792ccfd2caebbbf830",
          "md5": "abc9d35dcdaaeb07606969dfbc9814d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.4.1.jar",
          "url": "common-1.4.1.jar",
          "size": 10110,
          "sha512": "fa7507f565b502576128b53756a904a1c31c3af83c064c3db9bacebb51a5eee967a2cb3193b305946427ffea84ce417c6c78e9eb68063d14c89d17f07b12ae93",
          "sha256": "8f72f37bbf20e6a845c86f98d1211edff45eeabf15f7f45b0b276ac02d503ce1",
          "sha1": "71785ceb37efdfb8c1e078792ccfd2caebbbf830",
          "md5": "abc9d35dcdaaeb07606969dfbc9814d7"
        }
      ]
    }
  ]
}
