{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "spark-connect",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spark-connect-1.4.0.jar",
          "url": "spark-connect-1.4.0.jar",
          "size": 1023,
          "sha512": "1930d930f35a5cd7d783403419883d6a766a37bc5118be8a9699dc418ea7bb3a0c4092aacb0a52d687c5d1ebcc5d7c441cf4a352a2db8d0f947657e89d8e6f67",
          "sha256": "e05d8eec576dd7876fc38bdbb045b6f02b2b1af2aa169299dbf2e7a99d7fcab4",
          "sha1": "8e667e5909aae75d28fec0f33702dad928f7d8ce",
          "md5": "debdc1081a94b31cef89a69dde5b9674"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spark-connect-1.4.0.jar",
          "url": "spark-connect-1.4.0.jar",
          "size": 1023,
          "sha512": "1930d930f35a5cd7d783403419883d6a766a37bc5118be8a9699dc418ea7bb3a0c4092aacb0a52d687c5d1ebcc5d7c441cf4a352a2db8d0f947657e89d8e6f67",
          "sha256": "e05d8eec576dd7876fc38bdbb045b6f02b2b1af2aa169299dbf2e7a99d7fcab4",
          "sha1": "8e667e5909aae75d28fec0f33702dad928f7d8ce",
          "md5": "debdc1081a94b31cef89a69dde5b9674"
        }
      ]
    }
  ]
}
