{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "tools",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-1.4.4-empty.jar",
          "url": "tools-1.4.4-empty.jar",
          "size": 2338,
          "sha512": "023d19167949eb10628367f0f9d3354b8f093d0f50a184335f490432de25677e48c6920b658d1bebe5b485ec7a5abdb285e7eb97e55f4e5b4aa61348217a3f4c",
          "sha256": "3071099ccef743f9a42dcc50617b7e0011bb8a7ddc5ea10d3d96ff49c3c8d0b4",
          "sha1": "85ca26cb7d9dc9063bbd09abfb95225194117a13",
          "md5": "5850598902d73f893ef69b191dba079b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.4.4-empty.jar",
          "url": "tools-1.4.4-empty.jar",
          "size": 2338,
          "sha512": "023d19167949eb10628367f0f9d3354b8f093d0f50a184335f490432de25677e48c6920b658d1bebe5b485ec7a5abdb285e7eb97e55f4e5b4aa61348217a3f4c",
          "sha256": "3071099ccef743f9a42dcc50617b7e0011bb8a7ddc5ea10d3d96ff49c3c8d0b4",
          "sha1": "85ca26cb7d9dc9063bbd09abfb95225194117a13",
          "md5": "5850598902d73f893ef69b191dba079b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-1.4.4.jar",
          "url": "tools-1.4.4.jar",
          "size": 2672760,
          "sha512": "8400c8d36e082c97c8dbd8989a7fa3ecc2619d532adb17056ed6115d1fdc3edce81fa667487b7ccdde015527e8cbd077bbfe6c9878877a798e6db611d4389ab3",
          "sha256": "a64529ac9154a6e0caddac5268f63cd503ee11a1a0a46d38c10ba940d4fd5b3d",
          "sha1": "9ec5949483e19799cfc7cafd8e614e2ebbcdfe1d",
          "md5": "2518b540c3f61032166f854f6e26d0e3"
        }
      ]
    }
  ]
}
