{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.5.0.jar",
          "url": "jupyter-plugin-1.5.0.jar",
          "size": 16404,
          "sha512": "5f7ef5ebffc5e8ff92c39b499de3558a65918004c85e1f8b639f335f3e01022a386a8d87aeb3b709ba2b7b3f0864dedaf2c14a21f9666d035fa9d34b285302f2",
          "sha256": "34d1532bb5a3f624f7266940c5a7ad6f10f780508dd99fd3c0346830b4eb593f",
          "sha1": "161dec31e5d977d3e32667e14c43dadeb41327a1",
          "md5": "8a71c5c3b2e3dc79a84f717a6799b913"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.netapp.spark",
          "module": "tools",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.5.0.jar",
          "url": "jupyter-plugin-1.5.0.jar",
          "size": 16404,
          "sha512": "5f7ef5ebffc5e8ff92c39b499de3558a65918004c85e1f8b639f335f3e01022a386a8d87aeb3b709ba2b7b3f0864dedaf2c14a21f9666d035fa9d34b285302f2",
          "sha256": "34d1532bb5a3f624f7266940c5a7ad6f10f780508dd99fd3c0346830b4eb593f",
          "sha1": "161dec31e5d977d3e32667e14c43dadeb41327a1",
          "md5": "8a71c5c3b2e3dc79a84f717a6799b913"
        }
      ]
    }
  ]
}
