{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.5.0.jar",
          "url": "jupyter-plugin-1.5.0.jar",
          "size": 16165,
          "sha512": "836e6abfc66aeef3565fb439d39113354e928b0baa67101775e716e3565afba9f006f5c0776fc4c3490e8cb04b9f9dae4b5889b8d61420d49a42c540ff54b85e",
          "sha256": "5441577213d419886afc621ab4bb33d4c1a07e48251aeda8ecc64e4407bbd085",
          "sha1": "bb107f16ad2709fe1d323827ebc3e51ae77c7eb0",
          "md5": "3233cd581aa051cf99a3d4c66e0d255d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.netapp.spark",
          "module": "tools",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.5.0.jar",
          "url": "jupyter-plugin-1.5.0.jar",
          "size": 16165,
          "sha512": "836e6abfc66aeef3565fb439d39113354e928b0baa67101775e716e3565afba9f006f5c0776fc4c3490e8cb04b9f9dae4b5889b8d61420d49a42c540ff54b85e",
          "sha256": "5441577213d419886afc621ab4bb33d4c1a07e48251aeda8ecc64e4407bbd085",
          "sha1": "bb107f16ad2709fe1d323827ebc3e51ae77c7eb0",
          "md5": "3233cd581aa051cf99a3d4c66e0d255d"
        }
      ]
    }
  ]
}
