{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "tools",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-1.4.5-empty.jar",
          "url": "tools-1.4.5-empty.jar",
          "size": 2840,
          "sha512": "780d7e20a19c6b070eac5af56bab18adc60d2d5f59eb125134a25aa79549991077b3e5d75abcbcd763cb8da8b4babc76b30abf7c895bbe3cafac36d534f35383",
          "sha256": "9f4a37c109491ef93be545fdc56f1415651d7c8459de26283b568ea9eb933934",
          "sha1": "6b9b207eed87f1dbef1b700c7ccd220ffe741273",
          "md5": "cdcbef3c6ccca2166f089488f91c62c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.4.5-empty.jar",
          "url": "tools-1.4.5-empty.jar",
          "size": 2840,
          "sha512": "780d7e20a19c6b070eac5af56bab18adc60d2d5f59eb125134a25aa79549991077b3e5d75abcbcd763cb8da8b4babc76b30abf7c895bbe3cafac36d534f35383",
          "sha256": "9f4a37c109491ef93be545fdc56f1415651d7c8459de26283b568ea9eb933934",
          "sha1": "6b9b207eed87f1dbef1b700c7ccd220ffe741273",
          "md5": "cdcbef3c6ccca2166f089488f91c62c4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-1.4.5.jar",
          "url": "tools-1.4.5.jar",
          "size": 2673263,
          "sha512": "ee03d14499177078ca2fe045f14daa74e30e95c80879abde5f0471e2be3b40054756bf8872087d65df5df5ceb7d1fd0fedce1899a7fdd14db26f9f5f011e30f4",
          "sha256": "bd8dc87cab155fd6436c04e8d19ccb01246089a403a108a887e23c9095cf3cf1",
          "sha1": "68c626c1b73ad2f3560f3b37593ebb94f6b6b0c8",
          "md5": "a89d4610113f162341183ba8eb26c599"
        }
      ]
    }
  ]
}
