{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "tools",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-1.4.5-empty.jar",
          "url": "tools-1.4.5-empty.jar",
          "size": 2841,
          "sha512": "8e65690d70e8c34dafb5e98b1ce7b65dd6898aad3ec2ad136bd4ac0897db00962f4b2a91591fd38f2e4b2901ab4946c668b21b0b722fbbc83b9001a8896afe12",
          "sha256": "c7456017b8835a43f71b5d486f2e11f02fa2381a01f12a2f5aaef321f672242b",
          "sha1": "d1000bb8b067732c95e39d99a5cf58c424756dc0",
          "md5": "53074125fa0dd809331e48fc40446626"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        }
      ],
      "files": [
        {
          "name": "tools-1.4.5-empty.jar",
          "url": "tools-1.4.5-empty.jar",
          "size": 2841,
          "sha512": "8e65690d70e8c34dafb5e98b1ce7b65dd6898aad3ec2ad136bd4ac0897db00962f4b2a91591fd38f2e4b2901ab4946c668b21b0b722fbbc83b9001a8896afe12",
          "sha256": "c7456017b8835a43f71b5d486f2e11f02fa2381a01f12a2f5aaef321f672242b",
          "sha1": "d1000bb8b067732c95e39d99a5cf58c424756dc0",
          "md5": "53074125fa0dd809331e48fc40446626"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-1.4.5.jar",
          "url": "tools-1.4.5.jar",
          "size": 2673263,
          "sha512": "2e0b6aba689af366e3e94f53a5bceca94bf8a6fa3136022b5242e6b467219337f122ef23b68d6ed0e825513888fe69b1f6c60b8636c8740f7c686517214e79fa",
          "sha256": "7ca52dc88ee71b05751042c8d2569adb71f436a38850dc854ebe0419e6620194",
          "sha1": "35e70fcf2b7304b50e7eb228a740b0b0c757b952",
          "md5": "711287c47edaf982c6ad74d2f2441e53"
        }
      ]
    }
  ]
}
