{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "vscode-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vscode-plugin-1.0.0.jar",
          "url": "vscode-plugin-1.0.0.jar",
          "size": 14283,
          "sha512": "cd18ebce573b7ca13d650d8257e19c64cb54b8a784e798ddd7f7b007dcafa696afae189bc760cc981246e5a279b5944de43114f0996fe4534aaf55f8a7b68d65",
          "sha256": "2ae629cda572114af168d904013878d62a627c5c2f90114c51506a2ebc078329",
          "sha1": "175e1c76111cf4f9f4965fa858d9a9e655a91fa7",
          "md5": "458cd08653710fb43054dfb3c8d9d37f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.5.1-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "vscode-plugin-1.0.0.jar",
          "url": "vscode-plugin-1.0.0.jar",
          "size": 14283,
          "sha512": "cd18ebce573b7ca13d650d8257e19c64cb54b8a784e798ddd7f7b007dcafa696afae189bc760cc981246e5a279b5944de43114f0996fe4534aaf55f8a7b68d65",
          "sha256": "2ae629cda572114af168d904013878d62a627c5c2f90114c51506a2ebc078329",
          "sha1": "175e1c76111cf4f9f4965fa858d9a9e655a91fa7",
          "md5": "458cd08653710fb43054dfb3c8d9d37f"
        }
      ]
    }
  ]
}
