{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "vscode-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vscode-plugin-1.0.0.jar",
          "url": "vscode-plugin-1.0.0.jar",
          "size": 15647,
          "sha512": "34d3b196897d2a19c486f80fa40577821c8397447278e08ac33d7c7d7527c2f21d7705e61d29aaba4dfdb6db297c2e03d698c242fdfce6d07fc0d801678c9a63",
          "sha256": "93a81ff1c73715295400da7f84fb8f620120afb67517bb2e3df371106b116539",
          "sha1": "f25bbf1460a6a542a676af7cea20c9fd63b3c4bc",
          "md5": "3a44c8f3a88366540d854f8df1592423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.5.1-SNAPSHOT"
          }
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "2.3.10.Final"
          }
        }
      ],
      "files": [
        {
          "name": "vscode-plugin-1.0.0.jar",
          "url": "vscode-plugin-1.0.0.jar",
          "size": 15647,
          "sha512": "34d3b196897d2a19c486f80fa40577821c8397447278e08ac33d7c7d7527c2f21d7705e61d29aaba4dfdb6db297c2e03d698c242fdfce6d07fc0d801678c9a63",
          "sha256": "93a81ff1c73715295400da7f84fb8f620120afb67517bb2e3df371106b116539",
          "sha1": "f25bbf1460a6a542a676af7cea20c9fd63b3c4bc",
          "md5": "3a44c8f3a88366540d854f8df1592423"
        }
      ]
    }
  ]
}
