{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.3.0.jar",
          "url": "jupyter-plugin-1.3.0.jar",
          "size": 13550,
          "sha512": "363c8f2ca41a81f00522556a91d15ca89c99e9206612ccd2e6ebaf93e2b5b5888a8576cd13c1b685d2600dcc2afe6b4d919afce16c49a49ed2046d7a7a0d2eec",
          "sha256": "0a6582c81c89c5426c4cf003de63822286f6a4f36286218c9439ac76e2d4ab88",
          "sha1": "8ca01cca6a26c6c4d94ddd4fdd7ac9f1444d3f0a",
          "md5": "103cba20840ed65fac8fe8af018ef141"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.3.0.jar",
          "url": "jupyter-plugin-1.3.0.jar",
          "size": 13550,
          "sha512": "363c8f2ca41a81f00522556a91d15ca89c99e9206612ccd2e6ebaf93e2b5b5888a8576cd13c1b685d2600dcc2afe6b4d919afce16c49a49ed2046d7a7a0d2eec",
          "sha256": "0a6582c81c89c5426c4cf003de63822286f6a4f36286218c9439ac76e2d4ab88",
          "sha1": "8ca01cca6a26c6c4d94ddd4fdd7ac9f1444d3f0a",
          "md5": "103cba20840ed65fac8fe8af018ef141"
        }
      ]
    }
  ]
}
