{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.4.0.jar",
          "url": "common-1.4.0.jar",
          "size": 10110,
          "sha512": "baddb6c568c5e1cf0ca00d3892770f43f14a2fe5ce86fa479e45d92151d719f8c55b25fef5d3cbfd99aac7be19f44a3f6ee56ffe42701cc8e7b2534a9696d584",
          "sha256": "ec3cd5a970e1e2063a0d903c79d6dcb7750a00b1ad1a5f5d819fa8a2f13a39ac",
          "sha1": "71f2402c293f4db493015cd43604dedab61098b1",
          "md5": "c51a93958660c4340cfb0503f9869834"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.4.0.jar",
          "url": "common-1.4.0.jar",
          "size": 10110,
          "sha512": "baddb6c568c5e1cf0ca00d3892770f43f14a2fe5ce86fa479e45d92151d719f8c55b25fef5d3cbfd99aac7be19f44a3f6ee56ffe42701cc8e7b2534a9696d584",
          "sha256": "ec3cd5a970e1e2063a0d903c79d6dcb7750a00b1ad1a5f5d819fa8a2f13a39ac",
          "sha1": "71f2402c293f4db493015cd43604dedab61098b1",
          "md5": "c51a93958660c4340cfb0503f9869834"
        }
      ]
    }
  ]
}
