{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.5.0.jar",
          "url": "common-1.5.0.jar",
          "size": 17062,
          "sha512": "2f4ec5b5926bcbd3b76425928813208576fe47430a1894d45be722cb43bbb2b8974169bc18116a7f001adb755a9996577110c49160e1e43070112476795cb9b0",
          "sha256": "2797925839f179ae983560044c911a2d63016e3eca108d3a8590fc64d1bfff94",
          "sha1": "5ab84473426c592b0cf13f2b31070221cb4667a9",
          "md5": "de094dac0f65f00f2fd8b1b242142e77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "tools",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "7.0.0.202409031743-r"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.5.0.jar",
          "url": "common-1.5.0.jar",
          "size": 17062,
          "sha512": "2f4ec5b5926bcbd3b76425928813208576fe47430a1894d45be722cb43bbb2b8974169bc18116a7f001adb755a9996577110c49160e1e43070112476795cb9b0",
          "sha256": "2797925839f179ae983560044c911a2d63016e3eca108d3a8590fc64d1bfff94",
          "sha1": "5ab84473426c592b0cf13f2b31070221cb4667a9",
          "md5": "de094dac0f65f00f2fd8b1b242142e77"
        }
      ]
    }
  ]
}
