{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "common",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.5.0.jar",
          "url": "common-1.5.0.jar",
          "size": 17045,
          "sha512": "ec970751ce3a97fb4643ce41ff849a6e231dbefa4f270e6ad204c61f1825c6599a712ba3dfbf0a4f4c2f67938c9cad8806b70c35b31b6467db9924a3b90dacf9",
          "sha256": "404064bff376687dce7fabf84b914619f47c1036ee32c385bec7bbeb4d7a3fe5",
          "sha1": "8179f6ef62936a2a23501ba37c4349df7f2caab9",
          "md5": "27b76be99d442087fb927f844c48d5fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "tools",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "7.0.0.202409031743-r"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.5.0.jar",
          "url": "common-1.5.0.jar",
          "size": 17045,
          "sha512": "ec970751ce3a97fb4643ce41ff849a6e231dbefa4f270e6ad204c61f1825c6599a712ba3dfbf0a4f4c2f67938c9cad8806b70c35b31b6467db9924a3b90dacf9",
          "sha256": "404064bff376687dce7fabf84b914619f47c1036ee32c385bec7bbeb4d7a3fe5",
          "sha1": "8179f6ef62936a2a23501ba37c4349df7f2caab9",
          "md5": "27b76be99d442087fb927f844c48d5fe"
        }
      ]
    }
  ]
}
