{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "spark-cluster",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spark-cluster-1.0.0.jar",
          "url": "spark-cluster-1.0.0.jar",
          "size": 2405,
          "sha512": "9aa182adc9fbfce5dfba9f58c7f9199fa8e544bb8b392cfae296eaf6b6b4e235bc52b0a84f28306a58ad81747499f1be14af535d52dfea3b3a47bc04bb766ff5",
          "sha256": "6695ef308097b656104e5e4b329af95af86b3ad72b0880e38039ee5870522d78",
          "sha1": "8d4d97a22cebbad295570e7916c127649049ef9f",
          "md5": "4558189f2d00367847b25ff41bd13929"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spark-cluster-1.0.0.jar",
          "url": "spark-cluster-1.0.0.jar",
          "size": 2405,
          "sha512": "9aa182adc9fbfce5dfba9f58c7f9199fa8e544bb8b392cfae296eaf6b6b4e235bc52b0a84f28306a58ad81747499f1be14af535d52dfea3b3a47bc04bb766ff5",
          "sha256": "6695ef308097b656104e5e4b329af95af86b3ad72b0880e38039ee5870522d78",
          "sha1": "8d4d97a22cebbad295570e7916c127649049ef9f",
          "md5": "4558189f2d00367847b25ff41bd13929"
        }
      ]
    }
  ]
}
