{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.4.5.jar",
          "url": "jupyter-plugin-1.4.5.jar",
          "size": 11102,
          "sha512": "9f1af3155f92003cbf35cceadbfc8a8cf67dfb05e0680b958e6a030a771830ec7e430d5029d35922aae918a95a21715527d75f4ffedcb1c974ce5b46b19745de",
          "sha256": "a32dc782f3ed18877cd61e5cd57b27adfb033dc6a4c9028afb85980ff9049c76",
          "sha1": "67a44517969c0d3fe517cd6e788f9f26ed72b9a4",
          "md5": "ec852be930d89c42d87350f4af781e76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "com.netapp.spark",
          "module": "tools",
          "version": {
            "requires": "1.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.4.5.jar",
          "url": "jupyter-plugin-1.4.5.jar",
          "size": 11102,
          "sha512": "9f1af3155f92003cbf35cceadbfc8a8cf67dfb05e0680b958e6a030a771830ec7e430d5029d35922aae918a95a21715527d75f4ffedcb1c974ce5b46b19745de",
          "sha256": "a32dc782f3ed18877cd61e5cd57b27adfb033dc6a4c9028afb85980ff9049c76",
          "sha1": "67a44517969c0d3fe517cd6e788f9f26ed72b9a4",
          "md5": "ec852be930d89c42d87350f4af781e76"
        }
      ]
    }
  ]
}
