{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.4.5.jar",
          "url": "jupyter-plugin-1.4.5.jar",
          "size": 11091,
          "sha512": "b20c20617153747a17539e2b27a50d330fa0e466464a365b5e9db7ff5279d5f55eeeab5e43676b710ab66412d940fbb1e2a84ae8657cbf25ff5566799bc0816f",
          "sha256": "047771c0c1386ee968502bd48c95f04ade46f27f0af3dcd95be824518637ab29",
          "sha1": "e4a768e1d840f6ef5fa559c8b95a94af7b6068c8",
          "md5": "2d9a5700f1076776f658b5f2573ddf42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "com.netapp.spark",
          "module": "tools",
          "version": {
            "requires": "1.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.4.5.jar",
          "url": "jupyter-plugin-1.4.5.jar",
          "size": 11091,
          "sha512": "b20c20617153747a17539e2b27a50d330fa0e466464a365b5e9db7ff5279d5f55eeeab5e43676b710ab66412d940fbb1e2a84ae8657cbf25ff5566799bc0816f",
          "sha256": "047771c0c1386ee968502bd48c95f04ade46f27f0af3dcd95be824518637ab29",
          "sha1": "e4a768e1d840f6ef5fa559c8b95a94af7b6068c8",
          "md5": "2d9a5700f1076776f658b5f2573ddf42"
        }
      ]
    }
  ]
}
