{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "spark-netapp-shuffle",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spark-netapp-shuffle-1.0.0.jar",
          "url": "spark-netapp-shuffle-1.0.0.jar",
          "size": 109755,
          "sha512": "555e248156afca105af392c88523e40cce349f0acf1865be3e9cecbc6a271b7ffcd2b87f0c0ce312d1ea333bf7235f59f8e1880a521168dfbd120696bf964e34",
          "sha256": "25e200f614b3c0a666b701189e587a764640965e10d47657595366bf4d1b3ea0",
          "sha1": "31882609e46501aeea3ccdba74ac0903788a5e65",
          "md5": "b83f75f6a7eb065fef8360f154405ad3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "vscode-plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-core_2.12",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-sql_2.12",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-kubernetes_2.12",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.apache.spark",
          "module": "spark-connect_2.12",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.apache.hadoop",
          "module": "hadoop-aws",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.apache.hadoop",
          "module": "hadoop-hdfs",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "org.scala-lang.modules",
          "module": "scala-collection-compat_2.12",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "spark-netapp-shuffle-1.0.0.jar",
          "url": "spark-netapp-shuffle-1.0.0.jar",
          "size": 109755,
          "sha512": "555e248156afca105af392c88523e40cce349f0acf1865be3e9cecbc6a271b7ffcd2b87f0c0ce312d1ea333bf7235f59f8e1880a521168dfbd120696bf964e34",
          "sha256": "25e200f614b3c0a666b701189e587a764640965e10d47657595366bf4d1b3ea0",
          "sha1": "31882609e46501aeea3ccdba74ac0903788a5e65",
          "md5": "b83f75f6a7eb065fef8360f154405ad3"
        }
      ]
    }
  ]
}
