{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netapp.spark",
    "module": "jupyter-plugin",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jupyter-plugin-1.4.0.jar",
          "url": "jupyter-plugin-1.4.0.jar",
          "size": 13214,
          "sha512": "0484a76592c7dcf334557acd87b73813fb2c7b097b8a6f0d86737d20218c257acd5f985d569b294772a50f24e2919eac80b48a5e90b321518f16994d95fb7b78",
          "sha256": "cbe7f0fa4236c5486027950a0c9582946043873520937e4dd0bb3eec7c9d56a9",
          "sha1": "38b63c33f8ff8fba0c9f525135a34fa9cecff8cb",
          "md5": "2caa6a7ca4d5d15cf9492f6a004555ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.netapp.spark",
          "module": "common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "jupyter-plugin-1.4.0.jar",
          "url": "jupyter-plugin-1.4.0.jar",
          "size": 13214,
          "sha512": "0484a76592c7dcf334557acd87b73813fb2c7b097b8a6f0d86737d20218c257acd5f985d569b294772a50f24e2919eac80b48a5e90b321518f16994d95fb7b78",
          "sha256": "cbe7f0fa4236c5486027950a0c9582946043873520937e4dd0bb3eec7c9d56a9",
          "sha1": "38b63c33f8ff8fba0c9f525135a34fa9cecff8cb",
          "md5": "2caa6a7ca4d5d15cf9492f6a004555ea"
        }
      ]
    }
  ]
}
